### PR TITLE
When delve fails, stop the debug sessions

### LINKED ISSUE #492: Debugging a non-compiling app doesn't automatically end the debug session
## Repro
1. Apply the workaround in #474 on: VSCode 1.5.2, Go 1.7.1, Windows 10 Anniversary.
2. Create a simple hello world `main.go`.
3. Press <kbd>F5</kbd> and accept the defaults for `launch.json`.
4. Press <kbd>F5</kbd> and make sure that debugging works.
5. Add a simple compilation error (e.g. unused variable).
6. Press <kbd>F5</kbd>.
### Outcome

The app fails to compile, the debugger toolbar appears and the stop button must be clicked. The debug log shows `exit status 2`. The debugging session must be manually terminated.

Debug session is not terminated
### Expected Outcome

The app fails to compile and no debug session is started, or the debug session is automatically terminated.

### PR DESCRIPTION
**Pull request by ramya-rao-a**
Fixes #492

### CODE REVIEW

File: src/debugAdapter/goDebug.ts [hunk 1]
```diff
@@ -268,9 +269,11 @@ class Delve {
 					connectClient(port, host);
 				}
 			});
+			let that = this;
```
Comment (ramya-rao-a) [inline src/debugAdapter/goDebug.ts]: I am not sure why, but "this" in line 275 does not point to Delve object, it points to the ChildProcess which is why I had to resort to `that = this`

Comment (roblourens) [inline src/debugAdapter/goDebug.ts]: You can use a fat arrow function (`code => { ... }`) instead of `function`, then `this` will be correct

File: src/debugAdapter/goDebug.ts [hunk 2]
```diff
@@ -388,6 +391,10 @@ class GoDebugSession extends DebugSession {
 		this.delve.onstderr = (str: string) => {
 			this.sendEvent(new OutputEvent(str, 'stderr'));
 		};
+		this.delve.onclose = () => {
+			this.sendErrorResponse(response, 3000, 'Failed to continue: Check the debug console for details.');
```
Comment (roblourens) [inline src/debugAdapter/goDebug.ts]: Why 'failed to continue'?

File: src/debugAdapter/goDebug.ts (hunk 1 above)
Comment (ramya-rao-a) [inline src/debugAdapter/goDebug.ts]: Oh ya! doh!

File: src/debugAdapter/goDebug.ts (hunk 2 above)
Comment (ramya-rao-a) [inline src/debugAdapter/goDebug.ts]: Cos it matches with the other message for when the delve.connection fails?
