### PR TITLE
#2063 only suggest exported member name at start of comment

### LINKED ISSUE #2063: IntelliSense activates on single-line comments for exported symbols.
Steps to Reproduce:

Add to a comment on an exported name, using the period charater `.` will cause IntelliSense to activate.

Linked to https://github.com/Microsoft/vscode-go/issues/2006

### PR DESCRIPTION
**Pull request by kagof**
Resolves #2063 - only suggest the exported member name if the current comment has no content.

### CODE REVIEW

**Comment by rubenzinho07** [comment]
😈

Em Dom, 4 de nov de 2018 04:21, Karl Goffin <notifications@github.com>
escreveu:

File: src/goSuggest.ts [hunk 1]
```diff
@@ -133,15 +133,15 @@ export class GoCompletionItemProvider implements vscode.CompletionItemProvider {
...
-				if (lineCommentRegex.test(lineTillCurrentPosition) && position.line + 1 < document.lineCount) {
+				if (lineCommentFirstWordRegex.test(lineTillCurrentPosition) && position.line + 1 < document.lineCount) {
 					let nextLine = document.lineAt(position.line + 1).text.trim();
 					let memberType = nextLine.match(exportedMemberRegex);
 					let suggestionItem: vscode.CompletionItem;
 					if (memberType && memberType.length === 4) {
-						suggestionItem = new vscode.CompletionItem(memberType[3], vscodeKindFromGoCodeClass(memberType[1], ''));
+							suggestionItem = new vscode.CompletionItem(memberType[3], vscodeKindFromGoCodeClass(memberType[1], ''));
+						}
+						return resolve(suggestionItem ? [suggestionItem] : []);
```
Comment (ramya-rao-a) [inline src/goSuggest.ts]: Why was this return statement moved? With this change, when typing any text in the comments, we would end up calling gocode instead of exiting early

Comment (ramya-rao-a) [reply src/goSuggest.ts]: Also can you update the existing test case to reflect the bug fix? See https://github.com/Microsoft/vscode-go/blob/0.7.0/test/go.test.ts#L1014
