### PR TITLE
Fix prevention of completion popup in line comments. (fixes #1659)

### LINKED ISSUE #1659: The "." (dot) inside comment open the suggestion/completion list
Steps to Reproduce:

1.  Create comment on the right side of the code
2. Type "." (dot) and the completion list will opened

screen shot 2018-05-06 at 01 40 54

Expect: The completion should not appear since it's inside the comment

### PR DESCRIPTION
**Pull request by doxxx**
Fixes #1659 by checking for a line comment at the _end_ of the current line and also checking that the cursor position is within the line comment.

### CODE REVIEW

File: src/goSuggest.ts [hunk 1]
```diff
@@ -52,7 +52,9 @@ export class GoCompletionItemProvider implements vscode.CompletionItemProvider {
 				let lineTillCurrentPosition = lineText.substr(0, position.character);
 				let autocompleteUnimportedPackages = config['autocompleteUnimportedPackages'] === true && !lineText.match(/^(\s)*(import|package)(\s)+/);
 
-				if (lineText.match(/^\s*\/\//)) {
+				// prevent completion when typing in a line comment
+				const commentMatch = lineText.match(/\/\/.*$/);
```
Comment (ramya-rao-a) [inline src/goSuggest.ts]: why not just find the index directly using `lineText.indexOf('//')` ?

Comment (doxxx) [reply src/goSuggest.ts]: .... That's a very good point. :)

File: src/goSuggest.ts [hunk 2]
```diff
@@ -52,7 +52,9 @@ export class GoCompletionItemProvider implements vscode.CompletionItemProvider {
 				let lineTillCurrentPosition = lineText.substr(0, position.character);
 				let autocompleteUnimportedPackages = config['autocompleteUnimportedPackages'] === true && !lineText.match(/^(\s)*(import|package)(\s)+/);
 
-				if (lineText.match(/^\s*\/\//)) {
+				// prevent completion when typing in a line comment
+				const commentIndex = lineText.indexOf('//');
+				if (commentIndex > 0 && position.character > commentIndex) {
```
Comment (ramya-rao-a) [inline src/goSuggest.ts]: commentIndex being 0 is valid. This check should be `commentIndex > -1`
