### PR TITLE
Fixes #310 - install Missing Analysis Tool. Better feedback would be nice

### LINKED ISSUE #310: install Missing Analysis Tool. Better feedback would be nice.
on latest version.
I was wondering if the tool could give some basic confirmation that it ran ok :)
Its not that it failed for me this time, just a bit of a black hole of feedback.
Just something on the terminal below that says "all done and good" type of thing. Or had an issue with this ...

````
Fetching https://golang.org/x/tools/cmd/guru?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/guru?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/guru": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/guru?go-get=1
get "golang.org/x/tools/cmd/guru": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/tools/cmd/guru/serial?go-get=1
Parsing meta tags from https://golang.org/x/tools/cmd/guru/serial?go-get=1 (status code 200)
get "golang.org/x/tools/cmd/guru/serial": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/cmd/guru/serial?go-get=1
get "golang.org/x/tools/cmd/guru/serial": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ast/astutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/ast/astutil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/ast/astutil?go-get=1
get "golang.org/x/tools/go/ast/astutil": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/buildutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/buildutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/buildutil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/buildutil?go-get=1
get "golang.org/x/tools/go/buildutil": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/callgraph?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/callgraph?go-get=1 (status code 200)
get "golang.org/x/tools/go/callgraph": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/callgraph?go-get=1
get "golang.org/x/tools/go/callgraph": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/ssa?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ssa?go-get=1 (status code 200)
get "golang.org/x/tools/go/ssa": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/ssa?go-get=1
get "golang.org/x/tools/go/ssa": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/types/typeutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/types/typeutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/types/typeutil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/types/typeutil?go-get=1
get "golang.org/x/tools/go/types/typeutil": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/callgraph/static?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/callgraph/static?go-get=1 (status code 200)
get "golang.org/x/tools/go/callgraph/static": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/callgraph/static?go-get=1
get "golang.org/x/tools/go/callgraph/static": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/ssa/ssautil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ssa/ssautil?go-get=1 (status code 200)
get "golang.org/x/tools/go/ssa/ssautil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/ssa/ssautil?go-get=1
get "golang.org/x/tools/go/ssa/ssautil": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/loader?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/loader?go-get=1 (status code 200)
get "golang.org/x/tools/go/loader": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/loader?go-get=1
get "golang.org/x/tools/go/loader": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/go/pointer?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/pointer?go-get=1 (status code 200)
get "golang.org/x/tools/go/pointer": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/pointer?go-get=1
get "golang.org/x/tools/go/pointer": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/container/intsets?go-get=1
Parsing meta tags from https://golang.org/x/tools/container/intsets?go-get=1 (status code 200)
get "golang.org/x/tools/container/intsets": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/container/intsets?go-get=1
get "golang.org/x/tools/container/intsets": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools/refactor/importgraph?go-get=1
Parsing meta tags from https://golang.org/x/tools/refactor/importgraph?go-get=1 (status code 200)
get "golang.org/x/tools/refactor/importgraph": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/refactor/importgraph?go-get=1
get "golang.org/x/tools/refactor/importgraph": verifying non-authoritative meta tag
golang.org/x/tools/cmd/guru/serial
golang.org/x/tools/go/ssa
golang.org/x/tools/go/loader
golang.org/x/tools/container/intsets
golang.org/x/tools/go/ssa/ssautil
golang.org/x/tools/go/callgraph
golang.org/x/tools/go/pointer
golang.org/x/tools/go/callgraph/static
golang.org/x/tools/cmd/guru

```

### PR DESCRIPTION
**Pull request by benclarkwood**
This commit causes goInstallTools to log very differently than present.

Presently, goInstallTools just writes the output of stdout and stderr to the Go outputChannel.

This commit proposes logging _much_ less in the case of success, and only logging the cause of errors.

Let me know what you think @lukehoban.

(A total success)
```
Installing 9 missing tools
  gorename
  gopkgs
  gocode
  goreturns
  godef
  golint
  go-outline
  go-symbols
  guru

Installing gopkgs SUCCEEDED
Installing go-outline SUCCEEDED
Installing go-symbols SUCCEEDED
Installing godef SUCCEEDED
Installing gorename SUCCEEDED
Installing golint SUCCEEDED
Installing goreturns SUCCEEDED
Installing gocode SUCCEEDED
Installing guru SUCCEEDED

All tools successfully installed. You're ready to Go :).
```

(A failure)
```
Installing 9 missing tools
  gorename
  gopkgs
  gocode
  goreturns
  godef
  golint
  go-outline
  go-symbols
  guru

Installing go-outline FAILED
Installing gorename FAILED
Installing gopkgs FAILED
Installing go-symbols FAILED
Installing golint FAILED
Installing goreturns FAILED
Installing gocode FAILED
Installing godef FAILED
Installing guru FAILED

9 tools failed to install.

gorename:
Error: Command failed: go get -u -v golang.org/x/tools/cmd/gorename
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp: lookup golang.org: no such host
golang.org/x/tools (download)
# cd /Users/ben/Documents/gowork/src/golang.org/x/tools; git pull --ff-only
fatal: unable to access 'https://go.googlesource.com/tools/': Could not resolve host: go.googlesource.com
package golang.org/x/tools/cmd/gorename: exit status 1
Fetching https://golang.org/x/tools/cmd/gorename?go-get=1
https fetch failed: Get https://golang.org/x/tools/cmd/gorename?go-get=1: dial tcp: lookup golang.org: no such host
golang.org/x/tools (download)
# cd /Users/ben/Documents/gowork/src/golang.org/x/tools; git pull --ff-only
fatal: unable to access 'https://go.googlesource.com/tools/': Could not resolve host: go.googlesource.com
package golang.org/x/tools/cmd/gorename: exit status 1
```

NOTE: Didn't include every failure's output as they're all the same (no internet connection).

### CODE REVIEW

File: src/goInstallTools.ts [hunk 1]
```diff
@@ -26,15 +26,41 @@ let tools: { [key: string]: string } = {
...
-			outputChannel.append('exec error: ' + err);
+	outputChannel.clear();
+	outputChannel.appendLine('Installing ' + missing.length + ' missing tools');
+	missing.forEach((missingTool, index, missing) => {
+		outputChannel.appendLine('  ' + missingTool);
+	});
+
+	outputChannel.appendLine(''); // Blank line for spacing.
+
+	Promise.all(missing.map(tool => new Promise<string>((resolve, reject) => {
```
Comment (lukehoban) [inline src/goInstallTools.ts]: One thing I was meaning to look into/change was running these serially instead of in parallel.  I'm pretty sure `go get` has issues when multiple gets are run in parallel, and users have reported that the existing extension occasionally runs into errors.  Since you are making changes here - may make sense to also just change this to do the gets serially

File: src/goReferences.ts [hunk 2]
```diff
@@ -40,7 +40,7 @@ export class GoReferenceProvider implements vscode.ReferenceProvider {
 				try {
 					if (err && (<any>err).code === 'ENOENT') {
 						vscode.window.showInformationMessage('The "guru" command is not available.  Use "go get -v golang.org/x/tools/cmd/guru" to install.', 'Install').then(selected => {
-							installTool('guru');
+							installTools(['guru']);
```
Comment (lukehoban) [inline src/goReferences.ts]: FWIW -There's another open issue tracking adding this logic to all of the places where we put up an error about a tool not being available.  Would be great to address this as well either as part of this change or as a follow-on change.

File: src/goSuggest.ts [hunk 3]
```diff
@@ -60,6 +60,7 @@ export class GoCompletionItemProvider implements vscode.CompletionItemProvider {
 					currentWord = word.substr(0, position.character - wordAtPosition.start.character);
 				}
 
+
```
Comment (lukehoban) [inline src/goSuggest.ts]: not needed?

**Comment by lukehoban** [comment]
This looks great - big improvement!  Left a few comments on the code changes.

**Comment by lukehoban** [comment]
I've merged this along with a few additional improvements that address the issues I mentioned in review and fixed a few additional related issues.  Thanks again!
