### PR TITLE
goLanguageServer: set completion follow up command from middleware

### LINKED ISSUE #3075: How to disable parameter hints post completion when using gopls
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- 1.14
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.42.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- linux amd64

### Share the Go related settings you have added/edited

```
{
    "editor.parameterHints.enabled": false,
    "go.useLanguageServer": true
}
```

### Describe the bug
editor.parameterHints.enabled does not work,I want to disable parameter hints.
QQ截图20200228143509

### PR DESCRIPTION
**Pull request by hyangah**
Middleware checks both `editor.parameterHints.enabled` and
`[go].editor.parameterHints.enabled`. The language specific
config takes precedence as long as it is defined.

vscode.workspace.getConfiguration behaves differently when
querying the language-specific configuration section ('[go]')
so I couldn't query [go].editor.parameterHints directly using
getConfiguration.

Tested manually. (sorry)

Fixes #3075

### CODE REVIEW

**Comment by hyangah** [comment]
@stamblerre @ramya-rao-a

File: src/goLanguageServer.ts [hunk 1]
```diff
@@ -143,6 +144,44 @@ export async function registerLanguageFeatures(ctx: vscode.ExtensionContext) {
...
 					return next(document, token);
+				},
+				provideCompletionItem: (
+					document: vscode.TextDocument,
+					position: vscode.Position,
+					context: vscode.CompletionContext,
+					token: vscode.CancellationToken,
+					next: ProvideCompletionItemsSignature
+				) => {
+						const editorParamHintsEnabled = vscode.workspace.getConfiguration('editor.parameterHints', document.uri)['enabled'];
```
Comment (stamblerre) [inline src/goLanguageServer.ts]: Are these both necessary? I would think that the purpose of the `document.uri` parameter is to decide if the setting applies to the current file.

File: src/goLanguageServer.ts [hunk 2]
```diff
@@ -143,6 +144,44 @@ export async function registerLanguageFeatures(ctx: vscode.ExtensionContext) {
...
+						const goParamHintsEnabled = vscode.workspace.getConfiguration('[go]', document.uri)['editor.parameterHints.enabled'];
+
+						var paramHintsEnabled: boolean = false;
+						if (typeof goParamHintsEnabled === 'undefined') {
+							paramHintsEnabled = editorParamHintsEnabled;
+						} else {
+							paramHintsEnabled = goParamHintsEnabled;
+						}
+						var cmd: Command = undefined;
```
Comment (stamblerre) [inline src/goLanguageServer.ts]: is the `= undefined` part necessary?

File: src/goLanguageServer.ts [hunk 3]
```diff
@@ -143,6 +144,44 @@ export async function registerLanguageFeatures(ctx: vscode.ExtensionContext) {
...
+							r: vscode.CompletionItem[] | vscode.CompletionList | null | undefined):
+							vscode.CompletionItem[] | vscode.CompletionList | null | undefined {
+							if (r) {
+								(Array.isArray(r) ? r : r.items).forEach((i: vscode.CompletionItem) => {
+									i.command = cmd;
+								});
+							}
+							return r;
+						}
+						const isThenable = <T>(obj: vscode.ProviderResult<T>): obj is Thenable<T> => obj && (<any>obj)['then'];
```
Comment (stamblerre) [inline src/goLanguageServer.ts]: What does this do? I'm totally confused at this point :smile:

Comment (hyangah) [reply src/goLanguageServer.ts]: vscode.ProviderResult can be a simple T or Thenable<T>. So, if the result of `next` call is a promise (thenable that has 'then' property), we chain configureCommands call using 'then'.
If the result of `next` is not thenable, it's not a promise and there is no 'then'. So, simply invoke configureCommands and pass the result of the next.

File: src/goLanguageServer.ts (hunk 1 above)
Comment (hyangah) [reply src/goLanguageServer.ts]: That's what I thought but it didn't work that way. Good news is that [vscode 1.42 api](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42169/commits/15e3d9ed635760023f0cacdbe0d6710a4c814673) has ConfigurationScope that includes {languageId, uri} pair. If we use it, getConfiguration does the proper job (applying the language specific config on top). Added TODO.

File: src/goLanguageServer.ts [hunk 4]
```diff
@@ -143,6 +144,55 @@ export async function registerLanguageFeatures(ctx: vscode.ExtensionContext) {
...
+					let cmd: Command;
+					if (paramHintsEnabled) {
+						cmd = { title: 'triggerParameterHints', command: 'editor.action.triggerParameterHints' };
+					}
+
+					function configureCommands(
+						r: vscode.CompletionItem[] | vscode.CompletionList | null | undefined):
+						vscode.CompletionItem[] | vscode.CompletionList | null | undefined {
+						if (r) {
+							(Array.isArray(r) ? r : r.items).forEach((i: vscode.CompletionItem) => {
```
Comment (ramya-rao-a) [inline src/goLanguageServer.ts]: The `configureCommands()` function is typed in such a way that it takes null and undefined as well.
In those cases, you will get a TypeError as `Array.isArray(r)` will be false and there is an attempt to get to the `items` property

File: src/goLanguageServer.ts [hunk 5]
```diff
@@ -143,6 +144,55 @@ export async function registerLanguageFeatures(ctx: vscode.ExtensionContext) {
...
+								i.command = cmd;
+							});
+						}
+						return r;
```
Comment (ramya-rao-a) [inline src/goLanguageServer.ts]: Since all we want to do is to update a property on the completion items, we shouldn't need to return anything. The array passed in should be updated and ready to use

File: src/goLanguageServer.ts [hunk 6]
```diff
@@ -143,6 +144,55 @@ export async function registerLanguageFeatures(ctx: vscode.ExtensionContext) {
...
+					}
+					const ret = next(document, position, context, token);
+
+					const isThenable = <T>(obj: vscode.ProviderResult<T>): obj is Thenable<T> => obj && (<any>obj)['then'];
+					if (isThenable<vscode.CompletionItem[] | vscode.CompletionList | null | undefined>(ret)) {
```
Comment (ramya-rao-a) [inline src/goLanguageServer.ts]: Why are we expecting `ret` to be a thenable resolving to null or undefined?

File: src/goLanguageServer.ts (hunk 4 above)
Comment (hyangah) [reply src/goLanguageServer.ts]: but that's guarded by the above if (r), isn't it?

File: src/goLanguageServer.ts (hunk 6 above)
Comment (hyangah) [reply src/goLanguageServer.ts]: vscode.ProviderResult (the return type of next) allows null or undefined.

File: src/goLanguageServer.ts (hunk 4 above)
Comment (ramya-rao-a) [reply src/goLanguageServer.ts]: Ah! yes. Sorry, missed that

**Comment by ramya-rao-a** [comment]
If I understood the upstream conversations, it looks like `gopls` already calls `editor.action.triggerParameterHints` command. Won't we end up calling this command twice with the changes in this PR? 

Are we planning to remove the call to the command from `gopls`?

**Comment by stamblerre** [comment]
> Are we planning to remove the call to the command from `gopls`?

Yes. This will handle the fact that we can't respect user's configurations in `gopls`.

**Comment by ramya-rao-a** [comment]
My concern is for users that have this change in the extension, but uses the gopls that is also running the `editor.action.triggerParameterHints` command. So, wouldn't this command get triggered twice?

**Comment by hyangah** [comment]
> My concern is for users that have this change in the extension, but uses the gopls that is also running the `editor.action.triggerParameterHints` command. So, wouldn't this command get triggered twice?

There is only one command in each completion item and this PR is overriding it. 
So, basically, it's undoing what `gopls` did in line 183.
