### PR TITLE
Fix 'Debug: Start Without Debugging' to use current file and include buildFlags/args

### LINKED ISSUE #2086: Debug: Start without Debugging command doesn't use the args, buildflags from the debug configuration
`Debug: Start without Debugging` is the command to use to simply run the current file rather than debugging. 

This is expected to use the currently selected debug configuration in launch.json
It does use the `program` and `env` attributes as expected, but ignores the `args` and `buildflags` attributes.

PRs are most welcome to fix this.
Code Pointers:
- [Build and Debug extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- [Debug the debugger](
https://github.com/Microsoft/vscode-go/tree/master/src/debugAdapter)
- Update the `go run` call at https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L317 to use the args and buildflags

### PR DESCRIPTION
**Pull request by brycekahle**
Include buildFlags and args when running without debugging. Use current file (if there is one) when 'running without debugging'.

Fixes #2086 and #2085

### CODE REVIEW

File: src/debugAdapter/goDebug.ts [hunk 1]
```diff
@@ -209,6 +209,7 @@ interface LaunchRequestArguments extends DebugProtocol.LaunchRequestArguments {
 	dlvToolPath: string;
 	/** Delve Version */
 	apiVersion: number;
+	currentFile: string;
```
Comment (brycekahle) [inline src/debugAdapter/goDebug.ts]: @ramya-rao-a This was the only way to pass along `currentFile`, but this is obviously not configuration. Is it OK to not have `currentFile` in the schema in `package.json`?

**Comment by brycekahle** [comment]
The latest CI failure does not appear to be related.

File: src/debugAdapter/goDebug.ts (hunk 1 above)
Comment (ramya-rao-a) [reply src/debugAdapter/goDebug.ts]: Yes, its ok. In this case, this is an internal implementation. Current file can always be determined by VS Code using the `vscode.window.activeTextEditor`. It need not be provided by the user

**Comment by ramya-rao-a** [comment]
Thanks @brycekahle!
